# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/azure/app-service/app-service-plan-manage#create-an-app-service-plan
#
# To configure this workflow:
#
# 1. For Linux apps, add an app setting called WEBSITE_WEBDEPLOY_USE_SCM and set it to true in your app **before downloading the file**.
#      For more instructions see: https://docs.microsoft.com/azure/app-service/configure-common#configure-app-settings
#
# 2. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on: push
env:
  AZURE_WEBAPP_NAME: Microsoft.Web-WebApp-Portal-49545b9b-b77e    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'https://portal.azure.com/#blade/HubsExtension/DeploymentDetailsBlade/overview/id/%2Fsubscriptions%2Fafacb393-95b5-4f9c-9b45-b8fc61813cf4%2FresourceGroups%2FGroup4-P2%2Fproviders%2FMicrosoft.Resources%2Fdeployments%2FMicrosoft.Web-WebApp-Portal-49545b9b-b77e/packageId/Microsoft.WebSite/packageIconUri/https%3A%2F%2Fcatalogartifact.azureedge.net%2Fpublicartifacts%2FMicrosoft.WebSite-2.6.6%2FMedium.png/primaryResourceId/%2Fsubscriptions%2Fafacb393-95b5-4f9c-9b45-b8fc61813cf4%2Fresourcegroups%2FGroup4-P2%2Fproviders%2FMicrosoft.Web%2Fsites%2FChariots/provisioningHash/customize-post-provisioning-steps-webapp-deployment/createBlade/%7B"bladeName"%3A"AppServiceWebAppCreateV3Blade"%2C"extension"%3A"WebsitesExtension"%7D'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'  # set this to the node version to use
  
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --prod
        working-directory: ./client
      
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
